spellcheck:
	@ ( \
		misspell -error `find $(PROJECT_ROOT) -name '*.go'`; \
	);

%.compliant: spellcheck
	@ ( \
		pushd "$(PROJECT_ROOT)/$(subst .compliant,,$@)" >/dev/null || exit 1; \
		go fmt || exit 1; \
		GOPATH=$(PWD)/ golint || exit 1; \
		GOPATH=$(PWD)/ go vet || exit 1; \
	);
