CUR_DIR = $(shell pwd)

spellcheck:
	@ ( \
		misspell -error `find $(PROJECT_ROOT) -not -path '*/vendor/*' -name '*.go'`; \
	);

%.compliant: spellcheck
	@ ( \
		cd "$(PROJECT_ROOT)/$(subst .compliant,,$@)" >/dev/null || exit 1; \
		go fmt || exit 1; \
		GOPATH=$(CUR_DIR)/ golint || exit 1; \
		GOPATH=$(CUR_DIR)/ go vet || exit 1; \
	);
